<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Lengkapi Info Akun_bi bi-camera display-6</name>
   <tag></tag>
   <elementGuidId>28f49368-3878-47e2-9a2a-07fe8776b07b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form-avatar-input']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.bi.bi-camera.display-6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>245c46b2-407e-4240-95b4-648922ea6c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-camera display-6</value>
      <webElementGuid>2cbba849-5692-45ec-8eb4-bd5101ab5070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-avatar-input&quot;)/i[@class=&quot;bi bi-camera display-6&quot;]</value>
      <webElementGuid>e65ff03a-4339-4279-a862-af1360f96933</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-avatar-input']/i</value>
      <webElementGuid>309e6059-1e94-4c6c-b0cb-b73b2f3914a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/i</value>
      <webElementGuid>9743f485-642a-42ed-94f2-24a442daf616</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
