<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Product Image Preview</name>
   <tag></tag>
   <elementGuidId>44a37319-00d4-463b-a241-2679ecfce4db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='input-images']/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-preview</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dab10f73-926f-49b7-90d5-bfda79fcf0b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-preview</value>
      <webElementGuid>66b21210-598f-42d3-91a6-70837844e552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>blob:https://secondhand.binaracademy.org/fdf21e83-f824-4e5e-beb1-785970099530</value>
      <webElementGuid>5461c05f-6c8c-4945-a431-6e5bb59d2459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-images&quot;)/div[@class=&quot;form-image-preview position-relative rounded-4 overflow-hidden&quot;]/img[@class=&quot;img-preview&quot;]</value>
      <webElementGuid>3a836d1c-1cc1-4735-8004-a0f59695eca5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='input-images']/div/img</value>
      <webElementGuid>10fcd2c9-b240-4720-96e3-16bf74afb24b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'blob:https://secondhand.binaracademy.org/fdf21e83-f824-4e5e-beb1-785970099530')]</value>
      <webElementGuid>7cddccea-e9f7-44c2-a61f-ba198f5599b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/img</value>
      <webElementGuid>2008cddb-192f-40ad-934c-a385de665f77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'blob:https://secondhand.binaracademy.org/fdf21e83-f824-4e5e-beb1-785970099530']</value>
      <webElementGuid>8850c360-9f9d-4d30-9f0e-1810d59553e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
